### ISSUE TITLE
Federation

### ISSUE THREAD

**Issue by chriskolenko** [dotellie/apollo-metrics#4]
I'm having issues with metrics when I run the Apollo Gateway. 

Not sure how to debug TBH

**Comment by dotellie** [comment]
Hi there!

Could you tell me more about what exactly you're trying to accomplish? If you could tell me both what you expect to happen and what you are seeing that's going wrong (including any potential error messages) then that would help immensely! :smile:

**Comment by chriskolenko** [comment]
No no.. it was all me. 

Using NODE_ENV=production turns of introspection. 

This is why you don't debug things at 1-2am in the morning. 

Thanks, your library is very good. Everyone should be giving this a Star.!
